trigger:
- feature/Implementing-azure-pipeline
pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test package'
    #options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'SpringLabTest'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
  displayName: 'Maven'
- task: CmdLine@2
  inputs:
    script: |
      echo "pwd:"
      pwd
      echo "list"
      ls -lrt
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/target'
    ArtifactName: 'PublishedProject'
    publishLocation: 'Container'
