trigger:
- feature/Implementing-azure-pipeline
pool:
  vmImage: 'ubuntu-latest'
steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test package'
    #options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'SpringLabTest'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
  displayName: 'Maven'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'PublishedProject'
    publishLocation: 'Container'
#Tasks to create the needed infrastructure
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo 'Current directory'
      pwd
      echo 'List objects:'
      ls -lrt
- task: AzureCLI@2
  inputs:
    azureSubscription: 'mtr_arm_conn'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'target/create-resource-group.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    failOnStandardError: true