trigger:
- feature/Implementing-azure-pipeline
pool:
  vmImage: 'ubuntu-latest'
steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test package'
    #options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'SpringLabTest'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
  displayName: 'Maven'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'PublishedProject'
    publishLocation: 'Container'
#Tasks to create the needed infrastructure
- task: Bash@3
  displayName: 'DirectoryStructure'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo 'Current directory'
      pwd
      echo 'List objects:'
      ls -lrt
      cd target
      echo 'List of objects inside target:'
      ls -lrt
- task: AzureCLI@2
  displayName: 'ResourceGroupCreation'
  inputs:
    azureSubscription: 'mtr_arm_conn'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'target/create-resource-group.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    failOnStandardError: true
- task: Bash@3
  displayName: 'ParametersFileBofore'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    script: |
      echo 'Printing before replacement'
      cat target/parameters.json
- task: replace-variables-in-file@1
  displayName: 'ParametersReplacement'
  inputs:
    filepath: '$(System.DefaultWorkingDirectory)/target/parameters.json'
    contentToVariable: false
- task: Bash@3
  displayName: 'ParametersFileAfter'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    script: |
      echo 'Printing after replacement'
      cat target/parameters.json
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'AppServiceCreation'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'mtr_arm_conn'
    subscriptionId: 'd19f674d-e7be-4536-a190-7b50b24cd379'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mtr-$(AZ_ENV)-grp'
    location: '$(AZ_REGION)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/target/app-srv-template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/target/parameters.json'
    deploymentMode: 'Incremental'